# 2024年8月28日
name: Fork & Edit

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12,22 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: xNBOS/rule
        path: rule-repo


# Download files to Mihomo
    - name: Download files to Mihomo
      run: |
        mkdir -p rule-repo/Mihomo/Rules
        curl -L -o rule-repo/Mihomo/Rules/Metacubex.yaml "https://wiki.metacubex.one/example/mrs"
        

###### Commit
    - name: Add and Commits
      run: |
        cd rule-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
